name: Go

on:
  push:
    branches: [ working ]
  pull_request:
    branches: [ working ]

env:
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ github.token }}
    
jobs:

  populate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Upload complementary images to GHCR
      run: |
        echo $REGISTRY_PASSWORD | docker login $IMAGE_REGISTRY -u $REGISTRY_USER --password-stdin 
        export LIST='
          pause:3.7
          dns/k8s-dns-node-cache:1.21.1
          coredns/coredns:v1.8.6
          cpa/cluster-proportional-autoscaler-amd64:1.8.5
          metrics-server/metrics-server:v0.6.1
        '
        for IMAGE in $LIST
        do
          docker pull registry.k8s.io/$IMAGE
          docker tag registry.k8s.io/$IMAGE $IMAGE_REGISTRY/$IMAGE
          docker push $IMAGE_REGISTRY/$IMAGE
        done
        docker images

